import { fromJSON } from 'postcss'

export {default as DiseaseList} from '../pages/DiseaseList'
export {default as AddDisease} from '../pages/AddDisease'
export {default as DiseaseUpdate} from '../pages/DiseaseUpdate'
export {default as Create} from '../pages/Create'
export {default as Upload} from './Upload'
export {default as ViewPosts} from './ViewPosts'
export {default as AddTreatment} from '../pages/AddTreatment'
export {default as Model} from '../pages/Model'
export {default as TreatmentList} from '../pages/TreatmentList'
export {default as TreatmentUpdate} from '../pages/TreatmentUpdate'
export {default as TreatmentView} from '../pages/TreatmentView'
export {default as Map} from '../pages/Map'
export {default as Calculator} from '../pages/Calculator'
export {default as TreatmentPDF} from '../pages/TreatmentPDF'