export {default as DiseaseList} from '../pages/DiseaseList'
export {default as AddDisease} from '../pages/AddDisease'
export {default as DiseaseUpdate} from '../pages/DiseaseUpdate'
export {default as Create} from '../pages/Create'
export {default as Upload} from './Upload'
export {default as ViewPosts} from './ViewPosts'
export {default as AddTreatment} from '../pages/AddTreatment'